[gdrive] 
spreadsheet_id = "1rIAGVdMpfMLUFnznuPHXj9T7_I_katLoKlLshGbC2_I" 

client_email = "quanlycongviec14122025@thangnt09112025.iam.gserviceaccount.com" 

private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7Ia1vLTwMPlbN
yP1gCsrogv1cjJaMH/3OXdep0YU81G/fJd15Z83MbxGZF/iYw6r81Bc5q/9WxNJ0
usTiDtaucHwQQND3C3b5V7lWT4RQXZDY1VTMimDOIDGZiAZMedPIA2lhekZFxi5M
kjImBNndamSsUdq0CzsY1CM92C5F19eb/czAwwqLDSVVszUjqEM7EJfy6ayiD36i
rcH10AS/TF5y+W7dAf/EJMuxXaShbdQBqzi++nCNXqqMeWsxghmgA91oSrAwQS2D
y3bfb9kN9zGwTY3x5Ci/R6n+9tjFj4eShH8pwZFb2cjHj+jZokWBtnK0C5fZkO2W
o2yUrmf1AgMBAAECggEABv6WdPYqRtFHSiA3fqq1Z6tw8BykVxuuNboPbZGFrjH8
KUl8PCV2uivZavEY1NzuomfRcATPYaoWehzhCKVCJCygKbT1tCybIQbEyEazzPn/
IZuxTiCxLZzJpDhC9zWc7N6NYDXDZ3UMFfo0InR1kDxOnWirbz9cN7lckXTOUsRS
3ue+0/UrZ/973NNN2jKz2jk6Gkp+1PVcYFQCl2ElbDDTlzrMVF7DVvHde8nGpCRb
qR4KOhMOGAPaH1LJlONAcE/V1rBkPhdD7RwSdHGjUGb9v7CanIdB/g9CLK7w34Uy
9TnbeKQetWH5xNU6ypQFCg+kVH81XZ0WS/e59nhSAQKBgQD5gcthWR6EMNN5Rtrx
cFdSKZ9P4ekBNohlTif0dV3535UFtYYBDeWnDrsP01iOa1GajZjNWxI7HFPcl2p7
9ahy9WF4RlM+EUE7MZYK7pfNoJmnHQBtCu7orppPXvWdNfvTeHX2icoMRMdkIjcy
QHINLBZAN5blHYoryxCrZNA9xQKBgQDAAFcbwoWoQgMXoDz64+qlJCQUXXBqmWgx
UM27lyFHg+7iLnyWhziisC/q7nvjGF4gTRntzYi2tZAD+A6BaP5h56NB1pJ6eRgm
CKLSuLwlTISx1zGh9E6HPjHthqOuw0eH3zJpQzUfGgKYxePfQDBtX6u8VkvfCwcv
NUo78OzUcQKBgQCTbzUE0yqLJmbv9QSPQrj2ng27oFyVEOpMIoDNnUTo0Es40mja
2qFns/aphVOA5L2VvDIctsHxF+4eHYMYuLLPK1xrO/MYbA3Fsqlc0Fv3b/0bmLGV
va4q5HHekNhGC45BCZ97DTTNRx8jdmxzT02VpwWG8NJDlM7+zcGN5cZ/mQKBgQCa
E6vTqxZ3IAI7Q2usKppyS75oWVONN+5VJPL0RyN9sHJTL9rrMThR1fGeJiNk6nke
ksDsBLRhavJXPQjm8Mqy5qAshXSms+adHvELCRRzGiSiUn6R6OvbvB1070cLR8pv
Tr21mylV/Bl5X9Sto2U5YD0Atn/MTZ1GVQ1tbLmhAQKBgGhL28tiqpZtsX7H+GQW
p/x+4f4R7yKg3yll/U0qfsnLVUbQA7auzVw/4Z83BVUGlANna3vj9uC6CFz3yktb
WYjUIBL40Ye2uv49tl585blviApffd/0OMc2Fc4PgxAqOT3FDK4MsxWBjmNjWUKE
F2aO6TOEOQhwhoB0/gVXwYWY
-----END PRIVATE KEY-----"""
